### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by anatoly128** [robsonvleite/router#1]
You described how this works with apache. But how to configure with nginx?

**Comment by leocunhadev** [comment]
Tbm estou com essa duvida nessa questão, é possível?

**Comment by karvox** [comment]
O nginx não usa .htaccess, seria interessante um exemplo de código para habilitar o funcionamento do componente no nginx.

**Comment by rodrigorz** [comment]
Consegui fazer o rewrite da rota amigável funcionar no NGINX com esse comando:
```
if (!-e $request_filename) {
    rewrite ^(.*)$ /index.php?route=$1 last;
}
```

**Comment by DurvalPaicheco** [comment]
Boa!

> Consegui fazer o rewrite da rota amigável funcionar no NGINX com esse comando:
> 
> ```
> if (!-e $request_filename) {
>     rewrite ^(.*)$ /index.php?route=$1 last;
> }
> ```

**Comment by andreferreiraxl** [comment]
obrigado @rodrigorz . Para quem usa Azure, é importante colocar o startup command após ajustar o rewrite: cp /home/site/wwwroot/default /etc/nginx/sites-available/default && cp /home/site/wwwroot/default /etc/nginx/sites-enabled/default && service nginx reload

Fonte: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/configure-nginx-for-php-8-linux-azure-app-service/bc-p/3916344#M1452
