### ISSUE TITLE
Comportamento inesperado ao executar requisições na rota raiz quando os métodos GET e POST estão definidos na mesma.

### ISSUE THREAD

**Issue by giovannialo** [robsonvleite/router#13]
Certo dia me deparei com um problema que levei um tempinho para entender. 

Se na rota inicial (primária = null) for definido outro método junto de get(), por exemplo post(), quando uma requisição é feita na rota que não seja get(), ou seja, o post() citado acima, a rota do método get() também é executada.

```
$router->group(null);
$router->get('/', 'Web:login', 'web.login');
$router->post('/', 'Web:login', 'web.login');
```

Isso acontece devido a criação das rotas com/sem barra

```
https://localhost/meusite
https://localhost/meusite/
```

No final, ele executa o método diferente de get() na rota sem barra e, logo em seguida, executa o método get() na rota com /. isto também ocasiona falha na rota de post() e não é possível recuperar nenhuma informação do backend.

Abraços.

**Comment by robsonvleite** [comment]
Pode me dar um exemplo de como está disparando a requisição?
