### ISSUE TITLE
Nenhuma rota diferente de "/" funciona

### ISSUE THREAD

**Issue by welingtonfidelis** [robsonvleite/router#16]
Olá.
Eu estou tentando utilizar a biblioteca, segui inclusive um vídeo do autor mostrando como utilizar (https://www.youtube.com/watch?v=_7yG_K8gFbI). No entanto, qualquer rota diferente de "/" não funciona no meu projeto. Há alguma instrução que possa me dar sobre esse problema?

Php 7.2
CoffeeCode 1.0.7

**Comment by RuanScherer** [comment]
Anexe o código para que possa ser analisado, Welington. 😄

**Comment by TilsonM17** [comment]
Eu estou a passar pelo mesmo problema.
Segui a documentação, mas sem efeto positivo
