### ISSUE TITLE
Erro de redirecionamento com dados.

### ISSUE THREAD

**Issue by RuanScherer** [robsonvleite/router#18]
Ao redirecionar usando o método `redirect` os dados não são passados para o método do controlador da rota (o array de dados chega vazio). Segue trecho de código abaixo demonstrando:

```
public function register(array $data): void {
    echo $this->view->render("web/auth/register", $data);
}

public function handleRegister(): void {
    if (!$_POST["name"] || !$_POST["email"] || !$_POST["password"]) {
        $this->redirectWithError("/register", "Informe todos os dados.");
    } else {
        $data = (object) filter_input_array(INPUT_POST, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
        $users = (new User())->find("email = :email", "email={$data->email}")->count();
        if ($users) {
            $this->redirectWithError("/register", "Já existe um usuário cadastrado com o e-mail informado.");
        } else {
            $user = new User();
            $user->name = $data->name;
            $user->email = $data->email;
            $user->password = password_hash($data->password, PASSWORD_DEFAULT);
            $user->save();

            if ($user->fail()) {
                $this->redirectWithError("/register", "Erro ao cadastrar-se, tente novamente.");
            } else {
                $this->router->redirect("/app/home");
            }
        }
    }
}

public function redirectWithError(string $route, string $error) {
    var_dump($error);
    $this->router->redirect($route, ["error" => $error]);
}
```

**Comment by omnispecies** [comment]
Olá @RuanScherer , conseguiu resolver?
Estou com um problema parecido...

**Comment by RuanScherer** [comment]
Pior que não

**Comment by walissonhms** [comment]
@RuanScherer problema foi resolvido?

**Comment by omnispecies** [comment]
Meu problema era similar, e descobri que a solução estava no .htaccess

**Comment by brunobmorais** [comment]
Estou com  problema de ERR_TOO_MANY_REDIRECTS. Alguém sabe como resolver?

**Comment by walissonhms** [comment]
@brunomoraisti como você está colocando o redirecionamento?

**Comment by brunobmorais** [comment]
**Arquivo .htaccess**
RewriteEngine On
Options All -Indexes

## ROUTER WWW Redirect.
#RewriteCond %{HTTP_HOST} !^www\. [NC]
#RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

## ROUTER HTTPS Redirect
#RewriteCond %{HTTP:X-Forwarded-Proto} !https
#RewriteCond %{HTTPS} off
#RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# ROUTER URL Rewrite
RewriteCond %{SCRIPT_FILENAME} !-f
RewriteCond %{SCRIPT_FILENAME} !-d
RewriteRule ^(.*)$ index.php?route=/$1 [L,QSA]

**Comment by walissonhms** [comment]
> **Arquivo .htaccess**
> RewriteEngine On
> Options All -Indexes
> 
> ## ROUTER WWW Redirect.
> #RewriteCond %{HTTP_HOST} !^www. [NC]
> #RewriteRule ^ [https://www.%{HTTP_HOST}%{REQUEST_URI}](https://www.%%7BHTTP_HOST%7D%%7BREQUEST_URI%7D) [L,R=301]
> 
> ## ROUTER HTTPS Redirect
> #RewriteCond %{HTTP:X-Forwarded-Proto} !https
> #RewriteCond %{HTTPS} off
> #RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
> 
> # ROUTER URL Rewrite
> RewriteCond %{SCRIPT_FILENAME} !-f
> RewriteCond %{SCRIPT_FILENAME} !-d
> RewriteRule ^(.*)$ index.php?route=/$1 [L,QSA]

Seu .htaccess está correto. Já tentou acessar por outro navegador?

**Comment by omnispecies** [comment]
O meu tem funcionado assim

`RewriteCond %{REQUEST_URI} !^/index\.php`
`RewriteCond %{REQUEST_FILENAME} !-f`
`RewriteCond %{REQUEST_FILENAME} !-d`
`RewriteRule .* index.php [L]`
