### ISSUE TITLE
Redirecionamento

### ISSUE THREAD

**Issue by cacio** [robsonvleite/router#20]
Estou passando  para a rota no index o id com a tag {id} mas quando passo pra rota  
assim <?= $router->route("app.cadastroimoveis")."/{$value->id}" ; ?> ele cria assim http://localhost/projetos/Proda-Lcdpr_n/imoveis/cadimoveis/%7Bid%7D/3 e se eu coloco assim  <?= $router->route("app.cadastroimoveis")."{$value->id}" ; ?> 
ele cria http://localhost/projetos/Proda-Lcdpr_n/imoveis/cadimoveis/%7Bid%7D3 e dai na pagina eu tive que colocar uma função somente numeros pra pega o id que eu quero , só que acho que ta errado, no index eu coloco assim
 $route->group("imoveis");
 $route->get("/cadimoveis/{id}","App:cadastroImoveis","app.cadastroimoveis");
 
o que estou fazendo de errado ?

**Comment by walissonhms** [comment]
Tenta assim:
`route("app.cadastroimoveis", ["id" => $value->id])`

**Comment by cacio** [comment]
Ai tu foi gênio, funcionou , obrigado!.
