### ISSUE TITLE
Queria Usar com php 8

### ISSUE THREAD

**Issue by Hugo-Marinheiro** [robsonvleite/router#21]
Olá, estou a testar com php 8 mas não funciona, pode atualizar para php 8?

**Comment by curruwilla** [comment]
Aqui funciona, está dando algum erro aí? mostr pra gente

**Comment by debuggerTes** [comment]
![image](https://user-images.githubusercontent.com/76957059/103546331-93105180-4e81-11eb-9a8b-478f8f8ecf9a.png)

Só os packs de vocês que está dando esse bug..

**Comment by debuggerTes** [comment]
@Hugo-Marinheiro  cara consegui resolver o problema usando "composer install --ignore-platform-reqs."

**Comment by EtieneAdriano** [comment]
para resolver esse problema, tu podes usar uma versão falsa do php no teu composer.json
inves de 8 usa um versão anterior e ele instala normalmente

{
    "config": {
              "platform":{
                    "php":"7.2"
              }
     }
}

**Comment by EtieneAdriano** [comment]
`{
"config": {
"platform":{
"php":"7.2"
}
}
}`
