### ISSUE TITLE
readfile() com erro

### ISSUE THREAD

**Issue by icolamberti** [robsonvleite/router#23]
Estou tentando zipar alguns arquivos para download, mas tanto o arquivo zip quanto arquivos soltos são baixados com erro. Ainda vale dizer que no servidor o zip está lá perfeito. Acredito que o problema seja a não permissão de acesso, mas não consegui editar o .htaccess para que funcione. Existe algo além disso dentro do router?

**Comment by robsonvleite** [comment]
Verifique sua aplicação, teste rotas para arquivos compactados sem erros.
