### ISSUE TITLE
URL amigável no view

### ISSUE THREAD

**Issue by eborguezao** [robsonvleite/router#24]
Busquei na documentação e não encontrei, no view assumo uma url passando parâmetro que vem do banco com datalayer:

`<?php
echo "<a href='{$router->route('web.faq', ['category'=>$category['denomination']])}'>Categoria FAQ</a>";
?>`

e o link será **site.com/faq?category=anycategory**

Para a URL amigável fica feio, e não consigo passar o **category** como parte da URL em si, ex:
**site.com/faq/anycategory**

A rota em index.php: **$router->get("/faq/{category}", "Web:faq", "web.faq");**

Tentei feito o Laravel mas não obtive resultados, observei o código da classe, e não entendi como enviar para a rota a url desse modo.

Me dá um help, não sei onde recorrer para o suporte do componente.

**Comment by eborguezao** [comment]
Segunda vez que posto aqui e 'fuço' seus vídeos do baú e encontro a solução, exclui por favor.

**Comment by felipeabranches** [comment]
@eborguezao compartilha a solução aí 😄
