### ISSUE TITLE
Capturar os inputs em uma rota GET

### ISSUE THREAD

**Issue by minha-encomenda** [robsonvleite/router#29]
Bom dia, tenho um formulario para filtrar os dados. Quando eu faço o submit do formulario para uma rota usando o metodo POST, no controlador eu consigo acessar os dados na variavel $data. Porém se eu mudo o metodo para GET, o array $data chega null.

Será que estou fazendo algo errado?

Para contornar, incluir o trecho de código abaixo no metodo formSpoofing da classe Dispatch, ainda estou testando, mas aparentemente funcionou.

if ($this->httpMethod == "GET") {
            $queryString = filter_var(str_replace('?', "", strstr($_SERVER['REQUEST_URI'], "?")), FILTER_SANITIZE_STRIPPED);
            parse_str($queryString, $data);

            $this->data = $data;

            unset($this->data["_method"]);
            return;
        }

**Comment by robsonvleite** [comment]
Esse é o compotamento esperado @minha-encomenda, você pode fazer minha formação para aprender PHP do jeito certo e entender como tudo funciona. https://fsphp.com.br
