### ISSUE TITLE
Códigos de status de respostas HTTP

### ISSUE THREAD

**Issue by wilderamorim** [robsonvleite/router#3]
Favor implementar HTTP response status code. Ex.:
`header("HTTP/1.0 404 Not Found");`

**Comment by robsonvleite** [comment]
Se você tem uma rota 404 a resposta será 200 Wilder. Isso em uma camada web.

Se for tratar apenas com responde crie uma closure no arquivo de rotas e devolva o erro por http ao invés de usar o route redirect. :)

**Comment by wilderamorim** [comment]
@robsonvleite  Na verdade não, o código de resposta de uma página 404 deve ser 404.

Se você checar o SEO através deste site: https://www.woorank.com/pt/www/cafecontrol.com.br perceberá que há um erro, por não encontrar a página 404 do site.

```
O seu website não tem página de erro 404 personalizada.
O seu servidor tem uma resposta HTTP: 200
```

O que não acontece com este site: https://www.woorank.com/pt/www/webav.com.br

Também podemos conferir aqui https://httpstatus.io/ pesquisando por:

```
https://www.cafecontrol.com.br/ops/404
https://www.webav.com.br/ops/404
```

Eu resolvi isso passando o HTTP response status code dentro do método de erro do controlador, talvez fosse interessante vir nativamente no componente.
