### ISSUE TITLE
Criando sub dominio

### ISSUE THREAD

**Issue by tiagocaus** [robsonvleite/router#31]
Como configurar o sub domínio para carregar uma rota específica?

> https://dashboard.meudominio.com.local

```
/**
* Home page
*/
$router->group(null);
$router->get("/", "Web:home");
$router->get("/contact", "Web:contact");


/**
* Painel do sistema
*/
$router->group("dashboard");
$router->get("/", "Dashboard:login");
$router->get("/home", "Dashboard:home");
```

**Comment by tiagocaus** [comment]
Caso não tenha, é possivel fazer algo como:

https://route.thephpleague.com/5.x/routes/

```
$router = new League\Route\Router;

$router
    ->map('GET', '/acme/route', 'Acme\Controller::getMethod')
    ->setHost('dashboard.meudominio.com.local')
    ->setScheme('https');
```

**Comment by robsonvleite** [comment]
Dentro de dashboard você terá um novo index.php com as rotas do sub-domínio. Não é interessante misturar rotas em diferentes domínios da aplicação.
