### ISSUE TITLE
Rota e valor do parâmetro

### ISSUE THREAD

**Issue by maudrade** [robsonvleite/router#32]
Olá, boa tarde.
Estou tentando acessar uma rota com parâmetros, como exemplo abaixo.

Rota de acesso:
http://sistema.test/administrador/usuario/endereco/cadastro/{tipocadastro}/{id}

Rota de acesso com valor no parâmetro:
http://sistema.test/administrador/usuario/endereco/cadastro/usuario/2

Retorno da Array $data:
[tipocadastro] => 2 [id] => 

Estou tendo problema para passar o valor usuario no parâmetro, porque já consta na rota a palavra usuario.
O valor usuario esta sendo ignorado, então tipocadastro pega o valor do id, e o valor do id fica null.

Estou usando a versão 1.0

**Comment by robsonvleite** [comment]
Teste feito com

https://www.localhost/coffeecode/router/exemple/controller/oi/usuario/usuario/32498324

```php
$router->get("/oi/usuario/{editype}/{id}", function ($data){
    var_dump($data);
});
```

Retorno:

```php
array (size=2)
  'editype' => string '32498324' (length=8)
  'id' => null
```

Tudo certo.

**Comment by maudrade** [comment]
Boa noite Robson.
Como assim tudo certo ? 

O retorno não deveria ser
(size=2)
  'editype' => 'usuario'
  'id' =>  '32498324' 

Mas esta retornando null no id.
Não entendi bem.

Grato pela atenção.

**Comment by robsonvleite** [comment]
Hey, deveria sim. Correção sai na próxima versão. 😱

**Comment by maudrade** [comment]
Massa!!! 👍
Obrigado pela atenção.
