### ISSUE TITLE
Não é possível criar subgrupos?

### ISSUE THREAD

**Issue by helisoncruz** [robsonvleite/router#33]
```
$router->group('app');
$router->get('/', 'App:home', 'app.home');
$router->get('/logout', 'App:logout', 'app.logout');

$router->group('app/configs');
$router->get('/', 'Config:home', 'config.home');
```

Avaliando o código, vi que na função `group()` há um `str_replace()` que remove toda barra do valor inserido como parâmetro da função, transformando `app/configs` em `appconfigs`. Sei que bastaria fazer conforme abaixo que eu teria o mesmo resultado.

```
$router->group('app');
$router->get('/', 'App:home', 'app.home');
$router->get('/logout', 'App:logout', 'app.logout');
$router->get('/configs', 'Config:home', 'config.home');

```
Mas seria interessante ter, se não houver, uma função para criar subgrupos ou poder configurar da forma abaixo. Seria mais para questão de deixar mais explicito e organizado o código final.

```
$router->group('app');
$router->group('app/configs');
```

**Comment by robsonvleite** [comment]
Obrigado por reportar @helisoncruz , correção na próxima versão!

**Comment by helisoncruz** [comment]
Show, @robsonvleite isso vai bem legal, principalmente na leitura do código.
