### ISSUE TITLE
Controller error

### ISSUE THREAD

**Issue by alexolliveira** [robsonvleite/router#34]
Em quanto uso callback, funciona, mas quando eu chamo um  método lá no controller, nada aparece na tela

**Comment by MailsonPrates** [comment]
Veja se isso resolve
https://pt.stackoverflow.com/questions/463407/coffeecode-router-erro-400-em-todas-as-rotas

**Comment by robsonvleite** [comment]
Veja isso: https://www.youtube.com/watch?v=_7yG_K8gFbI&t=12s
