### ISSUE TITLE
Variável de idioma

### ISSUE THREAD

**Issue by tiagocaus** [robsonvleite/router#35]
Como faço para incluir uma vaiável que será o idioma do sistema.

Exemplo:
```
/**
* Home page
*/
$router->group("{lang}"); //pt-br, en, es
$router->get("/", "Web:home");
$router->get("/contact", "Web:contact");
```
Essa parte acima funciona bem, o acesso fica certinho.
> https://local.dev/pt/
> https://local.dev/pt/contact

Agora quando vou acessar outro local como: `https://local.dev/pt/dashboard/`

```
/**
* Painel do sistema
*/
$router->group("dashboard");
$router->get("/", "Dashboard:login");
$router->get("/home", "Dashboard:home");
```

Sempre vai para a tela de erro:
> https://local.dev/ops/404

**Comment by robsonvleite** [comment]
Sua segunda base de rotas leva para https://local.dev/dashboard/, não para https://local.dev/pt/dashboard/

**Comment by tiagocaus** [comment]
@robsonvleite Robson, a pergunta é como pode ser feito
