### ISSUE TITLE
Feature de Middleware

### ISSUE THREAD

**Issue by juliorsantos** [robsonvleite/router#38]
@robsonvleite o que acha de implementarmos uma feature de middleware?

Eu acho que seria ótimo para não precisar ficar poluindo o __construct do controller ou fazendo adaptações nas próprias rotas.

Aproveitando pra dizer que esse projeto é maravilhoso, eu já usei em diversos projetos aqui quando não uso Laravel.

Muito prático e rápido!!!

**Comment by robsonvleite** [comment]
Temos um pull sobre isso. Vai ser analisado em breve! 👊
