### ISSUE TITLE
Existe alguma forma de resgatar o nome da rota ou nome dela?

### ISSUE THREAD

**Issue by rafaellopes21** [robsonvleite/router#39]
Olá pessoa, estou com um projeto que tenho a necessidade de permissões por rota, e pra isso uso o nome da rota ou url no meu banco de dados para dar permissão.

Existe alguma maneira de dar um "$route->getRoute()" ou "$route->getName()" para obter o nome da rota?

Caso nao tenha, seria legal criar um método onde conseguimos obter o nome das nossas rotas e até mesmo os grupos a qual pertencem.

Obrigado.

**Comment by robsonvleite** [comment]
Implementado método current() para próxima versão.
