### ISSUE TITLE
Consigo usar o router para enviar dados em json?

### ISSUE THREAD

**Issue by marquesjuniorpalmas** [robsonvleite/router#41]
Boa Tarde,

Verifiquei que quando faço uma rota em POST ele vai em um array, mas eu precisaria que fosse enviado um json para a api tratar as informações e retornar o mesmo json.

Abs

**Comment by robsonvleite** [comment]
Basta tratar a saída e a entrada com json_enconde e json_decode @marquesjuniorpalmas.
