### ISSUE TITLE
Propertie $path from RouterTrait with php port

### ISSUE THREAD

**Issue by lrodolfol** [robsonvleite/router#43]
hi, my i'm rodolfo and i used this router. but when the server use port like: 8080 or other, the $path from Dispatch class not work with INPUT_GET. 
then, i tried fix-it and inserted this code:

``
        //new code
        $port = (filter_input(INPUT_SERVER, "SERVER_PORT", FILTER_DEFAULT) ?? "");
        $port = strpos($_SERVER['HTTP_HOST'], $port) ? $port : "";
        // end new code
        $this->projectUrl = (substr($projectUrl, "-1") == "/" ? substr($projectUrl, 0, -1) : $projectUrl);

        if($port) {
            $this->patch = (filter_input(INPUT_SERVER, "REQUEST_URI", FILTER_DEFAULT) ?? "/");
        }else{
            $this->patch = (filter_input(INPUT_GET, "route", FILTER_DEFAULT) ?? "/");
        }

        $this->separator = ($separator ?? ":");
        $this->httpMethod = $_SERVER['REQUEST_METHOD'];``

maybe this can by fix-it in the .htaccess! ?

**Comment by robsonvleite** [comment]
Please, use a virtual host
