### ISSUE TITLE
Middleware e controller

### ISSUE THREAD

**Issue by ClaudioSilvaBg** [robsonvleite/router#46]
Boa noite, é possível enviar um objeto da middleware para o controller?

A ideia seria verificar o usuário com a middleware e se encontrar enviar para o controller os dados desse usuário para que não seja necessário refazer isso no controller novamente, é possível? Se sim como posso enviar esses dados???

Desde já agradeço a ajuda

**Comment by robsonvleite** [comment]
Algum exemplo?
