### ISSUE TITLE
league/plates v4.0.0-alpha para v3.4.0 erro no create

### ISSUE THREAD

**Issue by tiagocaus** [robsonvleite/router#47]
Olá, estou fazendo um dowgrade no league/plates, de v4.0.0-alpha para v3.4.0, porque essa versão da suporte ao PHP 8.

Ao fazer essa mudança estou tendo problema nesse create:

IMG: https://i.imgur.com/fnsrTGz.png

Como corrigi-lo?

**Comment by giovannialo** [comment]
new Engine(args...)
