### ISSUE TITLE
Rotas apontando sempre pra " / "

### ISSUE THREAD

**Issue by lrodolfol** [robsonvleite/router#50]
Instalei o php no disco e subi o servidor com php -S localhost:8080 . Quando passo rotas como localhost:8080/sobre   /localhost:8080/blog  qualquer rota além de localhost:8080  ele sempre aponta pro home.

codigo do index:

`$router->namespace("source\Controllers");

$router->get("/", "Home:Index");
$router->get("/sobre", "Home:sobre");

$router->dispatch();`

**Comment by robsonvleite** [comment]
Verifique o rewrite engine da sua maquina e se está com o htaccess corretamente
