### ISSUE TITLE
Nginx não funciona

### ISSUE THREAD

**Issue by marquesjuniorpalmas** [robsonvleite/router#53]
Olá o router não renderiza as rotas, usando o nginx, o código informado na documentação não funciona, alguém conseguiu fazer funcionar?

Abs

**Comment by walissonhms** [comment]
Funciona tanto no Apache quanto Nginx, talvez pode ser o location
Eu uso ele no nginx com Docker

**Comment by marquesjuniorpalmas** [comment]
Qual a configuração do nginx que tu usou?
