### ISSUE TITLE
Retornando imagens

### ISSUE THREAD

**Issue by fausantosdev** [robsonvleite/router#7]
Valos lá. Com essa biblioteca eu criei uma api, e nessa  api eu faço uploads de imagens, para uma pasta interna chamada 'uploads', queria saber como eu faço para retornar essa imagem para ser usada em um front, pois na documentação não fala nada a respeito.
Na verdade seria bom retornar qualquer outro tipo de arquivo, isso é muito útil.

**Comment by robsonvleite** [comment]
Isso não é rota e sim filesystem meu velho. No componente uploader você tem maior referência sobre; A rota sempre vai ser -F e -D, o que é ignorar arquivos e diretórios para que eles sejam controlados pela aplicação.

**Comment by fausantosdev** [comment]
Consegui resolver no decorrer de sua playlist, valew hehe
